### ISSUE TITLE
Move this repo to Robotology Legacy?

### ISSUE THREAD

**Issue by gabrielenava** [robotology-legacy/mex-wholebodymodel#91]
After properly document it, if everybody agrees.

**Comment by traversaro** [comment]
Related to : https://github.com/robotology/mex-wholebodymodel/issues/90 .

**Comment by gabrielenava** [comment]
@traversaro @Ganimed in the end, can we proceed in moving the repo to legacy? I remember we discussed about moving the WBM-class in another repo, am I right?

**Comment by traversaro** [comment]
Ok for me.

**Comment by Ganimed** [comment]
Sorry, the last time I was quite busy. Yes, let's moving my branch into a new repository. Then we can put the _mex-wholebodymodel_-repo to the legacy branch.
So, when do have time that we can merge everything together into a new repo? Thanks.

**Comment by Ganimed** [comment]
Is it possible to make a new repository in _robotology_ called "wbm-library"? I don't know if I have the rights there to create a new repo. Thanks.

**Comment by traversaro** [comment]
Done.
